# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ericent.in
full_name: Eric Entin
email: eric@ericent.in
description: >
  Elixir team lead at FanDuel. Experienced with Elixir/Erlang, Haskell, Ruby,
  and C++. Elixir, Phoenix, Ecto, and Postgrex contributor.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ericent.in" # the base hostname & protocol for your site
twitter_username: antipax
github_username:  antipax

# Build settings
markdown: kramdown
